/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.MenuRespostasController;
import model.FuncaoDeOnda;

/**
 *
 * @author luana
 */
public class MenuRespostas extends javax.swing.JFrame {

    /**
     * Creates new form MenuRespostas
     */
    public MenuRespostas(FuncaoDeOnda f) {
        initComponents();
        setLocationRelativeTo(null);
        dados = f;
        control = new MenuRespostasController(this,dados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFq1 = new javax.swing.JLabel();
        lblFq = new javax.swing.JLabel();
        lblFq2 = new javax.swing.JLabel();
        lblFq3 = new javax.swing.JLabel();
        lblFq4 = new javax.swing.JLabel();
        lblFq5 = new javax.swing.JLabel();
        lblFq6 = new javax.swing.JLabel();
        lblFq7 = new javax.swing.JLabel();
        lblFq8 = new javax.swing.JLabel();
        btA = new javax.swing.JButton();
        btB = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btD = new javax.swing.JButton();
        btE = new javax.swing.JButton();
        btF = new javax.swing.JButton();
        btG = new javax.swing.JButton();
        btH = new javax.swing.JButton();
        lblFq9 = new javax.swing.JLabel();
        lblFq10 = new javax.swing.JLabel();
        btI = new javax.swing.JButton();
        btJ = new javax.swing.JButton();
        lblFq11 = new javax.swing.JLabel();
        btK = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        lblFq1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq1.setText("a) Função de onda quântica no SI dos dois níveis");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFq.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq.setText("b) Energia do nível quântico inicial (𝐸_𝑖) e final (𝐸_𝑓)");

        lblFq2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq2.setText("a) Função de onda quântica no SI dos dois níveis");

        lblFq3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq3.setText("c) Energia, frequência e lambda do fóton absorvido ou emitido pela partícula");

        lblFq4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq4.setText("d) Velocidade (𝑣) da partícula no nível quântico inicial e final");

        lblFq5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq5.setText("e) Comprimento de onda de De Broglie (𝜆_n) da partícula no nível quântico inicial e final");

        lblFq6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq6.setText("f) Probabilidade de encontrar a partícula, em %, entre 𝑎 e 𝑏 no nível inicial e final");

        lblFq7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq7.setText("g) Gráfico da função de onda para o nível inicial da particula");

        lblFq8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq8.setText("h) Gráfico da função de onda para o nível final da particula");

        btA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btA.setText("A");
        btA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAActionPerformed(evt);
            }
        });

        btB.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btB.setText("B");
        btB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBActionPerformed(evt);
            }
        });

        btC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btC.setText("C");
        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });

        btD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btD.setText("D");
        btD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDActionPerformed(evt);
            }
        });

        btE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btE.setText("E");
        btE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEActionPerformed(evt);
            }
        });

        btF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btF.setText("F");
        btF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFActionPerformed(evt);
            }
        });

        btG.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btG.setText("G");
        btG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGActionPerformed(evt);
            }
        });

        btH.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btH.setText("H");
        btH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHActionPerformed(evt);
            }
        });

        lblFq9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq9.setText("i) Gráfico da função distribuição de probabilidade para o nível inicial da partícula");

        lblFq10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq10.setText("j) Gráfico da função distribuição de probabilidade para o nível final da partícula");

        btI.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btI.setText("I");
        btI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIActionPerformed(evt);
            }
        });

        btJ.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btJ.setText("J");
        btJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJActionPerformed(evt);
            }
        });

        lblFq11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFq11.setText("k) Simulação");

        btK.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btK.setText("K");
        btK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKActionPerformed(evt);
            }
        });

        jMenu1.setText("Função de onda");

        jMenuItem1.setText("Entradas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFq)
                            .addComponent(lblFq3)
                            .addComponent(lblFq4)
                            .addComponent(lblFq5)
                            .addComponent(lblFq6)
                            .addComponent(lblFq7)
                            .addComponent(lblFq8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btK))
                            .addComponent(lblFq9)
                            .addComponent(lblFq10)
                            .addComponent(lblFq11))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblFq2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFq11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btI, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btJ, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btG, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAActionPerformed
        control.botaoA();
    }//GEN-LAST:event_btAActionPerformed

    private void btBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBActionPerformed
        control.botaoB();
    }//GEN-LAST:event_btBActionPerformed

    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        control.botaoC();
    }//GEN-LAST:event_btCActionPerformed

    private void btDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDActionPerformed
        control.botaoD();
    }//GEN-LAST:event_btDActionPerformed

    private void btEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEActionPerformed
        control.botaoE();
    }//GEN-LAST:event_btEActionPerformed

    private void btFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFActionPerformed
        control.botaoF();
    }//GEN-LAST:event_btFActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        EntradasMenu m = new EntradasMenu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGActionPerformed
        control.botaoG();
    }//GEN-LAST:event_btGActionPerformed

    private void btHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHActionPerformed
        control.botaoH();
    }//GEN-LAST:event_btHActionPerformed

    private void btIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIActionPerformed
        control.botaoI();
    }//GEN-LAST:event_btIActionPerformed

    private void btJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJActionPerformed
        control.botaoJ();
    }//GEN-LAST:event_btJActionPerformed

    private void btKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKActionPerformed
        Visao v = new Visao(dados);
        v.setVisible(true);
    }//GEN-LAST:event_btKActionPerformed

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuRespostas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuRespostas().setVisible(true);
//            }
//        });
//    }
    
    private FuncaoDeOnda dados;
    private MenuRespostasController control;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btA;
    private javax.swing.JButton btB;
    private javax.swing.JButton btC;
    private javax.swing.JButton btD;
    private javax.swing.JButton btE;
    private javax.swing.JButton btF;
    private javax.swing.JButton btG;
    private javax.swing.JButton btH;
    private javax.swing.JButton btI;
    private javax.swing.JButton btJ;
    private javax.swing.JButton btK;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblFq;
    private javax.swing.JLabel lblFq1;
    private javax.swing.JLabel lblFq10;
    private javax.swing.JLabel lblFq11;
    private javax.swing.JLabel lblFq2;
    private javax.swing.JLabel lblFq3;
    private javax.swing.JLabel lblFq4;
    private javax.swing.JLabel lblFq5;
    private javax.swing.JLabel lblFq6;
    private javax.swing.JLabel lblFq7;
    private javax.swing.JLabel lblFq8;
    private javax.swing.JLabel lblFq9;
    // End of variables declaration//GEN-END:variables
}
