/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ResultadosFuncao;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTextField;
/**
 *
 * @author luana
 */
public class ResultadosFuncaoOnda extends javax.swing.JFrame {

    /**
     * Creates new form ResultadosFuncaoOnda
     */
    public ResultadosFuncaoOnda() {
        initComponents();
        setLocationRelativeTo(null);
        ResultadosFuncao func = new ResultadosFuncao(this);
    }

    public ResultadosFuncao getController() {
        return controller;
    }

    public void setController(ResultadosFuncao controller) {
        this.controller = controller;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItemEntradas() {
        return jMenuItemEntradas;
    }

    public void setjMenuItemEntradas(JMenuItem jMenuItemEntradas) {
        this.jMenuItemEntradas = jMenuItemEntradas;
    }

    public JMenuItem getjMenuItemMenu() {
        return jMenuItemMenu;
    }

    public void setjMenuItemMenu(JMenuItem jMenuItemMenu) {
        this.jMenuItemMenu = jMenuItemMenu;
    }

    public JLabel getLblVarL() {
        return lblVarL;
    }

    public void setLblVarL(JLabel lblVarL) {
        this.lblVarL = lblVarL;
    }

    public JLabel getLblVarN() {
        return lblVarN;
    }

    public void setLblVarN(JLabel lblVarN) {
        this.lblVarN = lblVarN;
    }

    public JLabel getLblVarProb() {
        return lblVarProb;
    }

    public void setLblVarProb(JLabel lblVarProb) {
        this.lblVarProb = lblVarProb;
    }

    public JLabel getLbla() {
        return lbla;
    }

    public void setLbla(JLabel lbla) {
        this.lbla = lbla;
    }

    public JLabel getLblb() {
        return lblb;
    }

    public void setLblb(JLabel lblb) {
        this.lblb = lblb;
    }

    public JLabel getLblb1() {
        return lblb1;
    }

    public void setLblb1(JLabel lblb1) {
        this.lblb1 = lblb1;
    }

    public JLabel getLbldx() {
        return lbldx;
    }

    public void setLbldx(JLabel lbldx) {
        this.lbldx = lbldx;
    }

    public JLabel getLblm() {
        return lblm;
    }

    public void setLblm(JLabel lblm) {
        this.lblm = lblm;
    }

    public JTextField getTxtResultadoL() {
        return txtResultadoL;
    }

    public void setTxtResultadoL(JTextField txtResultadoL) {
        this.txtResultadoL = txtResultadoL;
    }

    public JTextField getTxtResultadoN() {
        return txtResultadoN;
    }

    public void setTxtResultadoN(JTextField txtResultadoN) {
        this.txtResultadoN = txtResultadoN;
    }

    public JTextField getTxtResultadoProb() {
        return txtResultadoProb;
    }

    public void setTxtResultadoProb(JTextField txtResultadoProb) {
        this.txtResultadoProb = txtResultadoProb;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblVarProb = new javax.swing.JLabel();
        lbla = new javax.swing.JLabel();
        lblb = new javax.swing.JLabel();
        lblb1 = new javax.swing.JLabel();
        txtResultadoL = new javax.swing.JTextField();
        txtResultadoN = new javax.swing.JTextField();
        txtResultadoProb = new javax.swing.JTextField();
        lblm = new javax.swing.JLabel();
        lbldx = new javax.swing.JLabel();
        lblVarL = new javax.swing.JLabel();
        lblVarN = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemEntradas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel1.setText("Resultados");

        lblVarProb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVarProb.setText("P(x)= ");

        lbla.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbla.setText("a)");

        lblb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblb.setText("b)");

        lblb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblb1.setText("c)");

        txtResultadoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoLActionPerformed(evt);
            }
        });

        lblm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblm.setText("m");

        lbldx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbldx.setText("dx");

        lblVarL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVarL.setText("L = ");

        lblVarN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVarN.setText("n = ");

        jMenu1.setText("Menu");

        jMenuItemMenu.setText("menu");
        jMenuItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Entradas");

        jMenuItemEntradas.setText("entradas");
        jMenuItemEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEntradasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemEntradas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblb1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVarProb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtResultadoProb, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblVarN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtResultadoN, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVarL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtResultadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblm, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldx, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbla)
                    .addComponent(txtResultadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblm)
                    .addComponent(lblVarL))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblb)
                    .addComponent(txtResultadoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVarN))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblb1)
                    .addComponent(txtResultadoProb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldx)
                    .addComponent(lblVarProb))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultadoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoLActionPerformed

    private void jMenuItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMenuActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemMenuActionPerformed

    private void jMenuItemEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEntradasActionPerformed
        Caixa c = new Caixa();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemEntradasActionPerformed

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ResultadosFuncaoOnda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ResultadosFuncaoOnda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ResultadosFuncaoOnda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ResultadosFuncaoOnda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ResultadosFuncaoOnda().setVisible(true);
//            }
//        });
//    }
    
    private ResultadosFuncao controller;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemEntradas;
    private javax.swing.JMenuItem jMenuItemMenu;
    private javax.swing.JLabel lblVarL;
    private javax.swing.JLabel lblVarN;
    private javax.swing.JLabel lblVarProb;
    private javax.swing.JLabel lbla;
    private javax.swing.JLabel lblb;
    private javax.swing.JLabel lblb1;
    private javax.swing.JLabel lbldx;
    private javax.swing.JLabel lblm;
    private javax.swing.JTextField txtResultadoL;
    private javax.swing.JTextField txtResultadoN;
    private javax.swing.JTextField txtResultadoProb;
    // End of variables declaration//GEN-END:variables
}
